"use strict";
exports.__esModule = true;
var Product_1 = require("./Product");
var Operations_1 = require("./Operations");
var item = new Operations_1.Operations();
var cart = [];
item.addToCart(cart, new Product_1.Product(1, 'Pencil', 20));
item.addToCart(cart, new Product_1.Product(2, 'Books', 50));
item.addToCart(cart, new Product_1.Product(3, 'Painting kit', 300));
item.addToCart(cart, new Product_1.Product(4, 'Toys', 500));
item.addToCart(cart, new Product_1.Product(5, 'Bag', 200));
console.log("The items in cart are::::");
item.printCart(cart);
var remItem = 3;
console.log("The items in cart after removing the item ==>Toys");
cart = item.removeFromCart(cart, "Toys");
item.printCart(cart);
